<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>91a398e9-7cef-4b55-8d32-833c54c69f80</elementGuidId>
    <imagePath></imagePath>
    <name>button_ContinueToShipping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"class_name": "MuiButton-startIcon MuiButton-iconSizeLarge css-wth0qt", "tag_name": "span"}, {"class_name": "MuiTouchRipple-root css-w0pj6f", "tag_name": "span"}], "css": ["[class=\"MuiButtonBase-root\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeLarge\\ MuiButton-containedSizeLarge\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeLarge\\ MuiButton-containedSizeLarge\\ css-110xwq5\"]"], "self": {"class_name": "MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge css-110xwq5"}, "smart": ["internal:role=button[name=\"Continue to shipping\"i]", "form &gt;&gt; internal:role=button"], "target_attributes": {"text": "CONTINUE TO SHIPPING", "type": "submit"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ css-110xwq5"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Continue to shipping"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>