<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bc1e580e-18c5-4d71-aa62-9d47a97f92e4</elementGuidId>
    <imagePath></imagePath>
    <name>input_Email2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [], "css": ["#\\:r0\\:"], "self": {"class_name": "MuiInputBase-input MuiInput-input css-mnn31"}, "smart": ["internal:label=\"Email *\"i"], "target_attributes": {"id": ":r0:", "label": "Email\u2009*", "name": "email", "type": "email"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/input[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r0\:</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Email *"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>