<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e2f19d5c-389d-49db-bda0-8798608111d0</elementGuidId>
    <imagePath></imagePath>
    <name>link_GooglePixel7Pro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(1) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/google-pixel-7-pro') and equals(@text,'Google Pixel 7 Pro')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Google Pixel 7 Pro"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/google-pixel-7-pro</value>
        <webElementGuid>53b5af50-49b8-444f-8c97-9e7299f20d74</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Google Pixel 7 Pro</value>
        <webElementGuid>53b5af50-49b8-444f-8c97-9e7299f20d74</webElementGuid>
    </webElementProperties>
</WebElementEntity>