<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c6d2ed1a-6717-43e7-a69d-a98722dc6674</elementGuidId>
    <imagePath></imagePath>
    <name>link_iPhone15FineWovenCase</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[5]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(5) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-iphone-15-finewoven-case-with-magsafe-taupe?category=99') and equals(@text,'iPhone 15 FineWoven Case with MagSafe - Taupe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="iPhone 15 FineWoven Case with"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-iphone-15-finewoven-case-with-magsafe-taupe?category=99</value>
        <webElementGuid>f3da0f07-8e52-4f27-af26-d0fe08fdd6bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 FineWoven Case with MagSafe - Taupe</value>
        <webElementGuid>f3da0f07-8e52-4f27-af26-d0fe08fdd6bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>