<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2e42b569-b0d1-4bbc-ad4c-bfb213cb3510</elementGuidId>
    <imagePath></imagePath>
    <name>link_mobileBrands</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__child-element"]:nth-child(${link_mobileBrands_nthChild}) &gt; [class="horizontal-menu__element\ is-link\ is-child"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/category/apple') and equals(@text,'Apple')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_mobileBrands_internalRoleLinkName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/category/apple</value>
        <webElementGuid>218cda9c-a351-4097-b069-09699cbd2ec1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Apple</value>
        <webElementGuid>218cda9c-a351-4097-b069-09699cbd2ec1</webElementGuid>
    </webElementProperties>
</WebElementEntity>