<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0727d02e-adb1-421f-afdc-f7609a666fa1</elementGuidId>
    <imagePath></imagePath>
    <name>link_productCategories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__child-element"]:nth-child(${link_productCategories_nthChild}) &gt; [class="horizontal-menu__element\ is-link\ is-child"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'category/${category_id}') and equals(@text,'Apple')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_productCategories_internalRoleLinkName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Apple</value>
        <webElementGuid>e1297c72-c76d-4940-9d70-ed45370b2c69</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>category/${{category_id}}</value>
        <webElementGuid>e1297c72-c76d-4940-9d70-ed45370b2c69</webElementGuid>
    </webElementProperties>
</WebElementEntity>