<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3847f252-c7da-45d5-a695-bb2c8075be23</elementGuidId>
    <imagePath></imagePath>
    <name>link_productModels</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${link_productModels_class}"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'product/${product_id}') and equals(@text,'Samsung Galaxy S23 Ultra Smartview Cases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="${link_productModels_internalRoleHeadingName}"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung Galaxy S23 Ultra Smartview Cases</value>
        <webElementGuid>2eeb17cb-9a76-4ed8-b44a-637415af3c45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>product/${{product_id}}</value>
        <webElementGuid>2eeb17cb-9a76-4ed8-b44a-637415af3c45</webElementGuid>
    </webElementProperties>
</WebElementEntity>