<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>16c45335-98c1-4cf5-9c0b-b73e48b79065</elementGuidId>
    <imagePath></imagePath>
    <name>link_productDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[5]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${link_productDetails_class}"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'product/${link_productDetails_product_id}') and equals(@text,'iPhone 15 FineWoven Case with MagSafe - Taupe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="${link_productDetails_internalRoleHeadingName}"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 FineWoven Case with MagSafe - Taupe</value>
        <webElementGuid>be071f09-408e-4ecb-bdd2-8d4b7c9f1080</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>product/${{link_productDetails_product_id}}</value>
        <webElementGuid>be071f09-408e-4ecb-bdd2-8d4b7c9f1080</webElementGuid>
    </webElementProperties>
</WebElementEntity>