<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f78bf00-8f1a-417c-b0a2-79c5293a6cb0</elementGuidId>
    <imagePath></imagePath>
    <name>action_place_order</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-action\ btn-anim"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/cart') and equals(@text,'Place an order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Place an order"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/cart</value>
        <webElementGuid>6ad2a150-ca3f-4ffa-b92c-a209ff93cd86</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Place an order</value>
        <webElementGuid>6ad2a150-ca3f-4ffa-b92c-a209ff93cd86</webElementGuid>
    </webElementProperties>
</WebElementEntity>