<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a2192752-d70d-48a1-863b-eb0286ad1c4e</elementGuidId>
    <imagePath></imagePath>
    <name>button_BuyNow2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"tag_name": "path"}], "css": ["[class=\"products__item\\ in-stock\\ products__item_3-in-row\"]:nth-child(2) [class=\"svg-inline--fa\\ fa-cart-plus\\ fa-w-18\\ \"]"], "self": {}, "smart": ["li &gt;&gt; internal:has-text=\"New!iPhone 15 Silicone Case\"i &gt;&gt; internal:role=button"], "target_attributes": {}, "xpath": "//html/body[1]/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[2]/div[2]/button[1]/*[name()='svg'][1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(2) [type="button"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li &gt;&gt; internal:has-text="New!iPhone 15 Silicone Case"i &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>