<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a5926ced-b340-44e4-bb70-4fdca16a52d7</elementGuidId>
    <imagePath></imagePath>
    <name>button_BuyNow</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"tag_name": "svg"}], "css": ["[class=\"products__item\\ in-stock\\ products__item_3-in-row\"]:nth-child(2) [type=\"button\"]"], "self": {"class_name": "btn btn-to-cart products__to-cart-btn"}, "smart": ["li &gt;&gt; internal:has-text=\"New!iPhone 15 Silicone Case\"i &gt;&gt; internal:role=button"], "target_attributes": {"text": "", "title": "Add to cart", "type": "button"}, "xpath": "//html/body[1]/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[2]/div[2]/button[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(2) [type="button"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li &gt;&gt; internal:has-text="New!iPhone 15 Silicone Case"i &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>