<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d1b04765-5d75-49fb-9fc8-8d32f4637637</elementGuidId>
    <imagePath></imagePath>
    <name>button_Buy</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"tag_name": "svg"}], "css": ["[class=\"btn\\ btn-action\\ btn-anim\\ btn-lg\"]"], "self": {"class_name": "btn btn-action btn-anim btn-lg"}, "smart": ["internal:role=button[name=\"Buy\"i]", "internal:role=dialog &gt;&gt; internal:role=button &gt;&gt; nth=3"], "target_attributes": {"text": " Buy", "title": "Buy", "type": "button"}, "xpath": "//html/body[1]/div[3]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/button[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-action\ btn-anim\ btn-lg"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Buy"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>