<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>48b26957-7c4b-4a90-b226-b751255a1c5a</elementGuidId>
    <imagePath></imagePath>
    <name>button_clear</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-secondary"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Clear')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Clear"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Clear</value>
        <webElementGuid>6ad2a150-ca3f-4ffa-b92c-a209ff93cd86</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>6ad2a150-ca3f-4ffa-b92c-a209ff93cd86</webElementGuid>
    </webElementProperties>
</WebElementEntity>