<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df9f255b-b777-4cc1-a615-f483364a3ff3</elementGuidId>
    <imagePath></imagePath>
    <name>link_PlaceAnOrder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"tag_name": "svg"}], "css": ["[class=\"btn\\ btn-action\\ btn-anim\"]"], "self": {"class_name": "btn btn-action btn-anim"}, "smart": ["internal:role=link[name=\"Place an order\"i]"], "target_attributes": {"href": "/cart", "text": " Place an order"}, "xpath": "//html/body[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/a[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-action\ btn-anim"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Place an order"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>