<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cd5044b8-f9f4-4634-9cec-a9910d225af6</elementGuidId>
    <imagePath></imagePath>
    <name>button_Remove</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[5]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cart-item\ row"]:nth-child(4) [class="btn\ btn-sm\ btn-outline-secondary"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Remove')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Remove"i] &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Remove</value>
        <webElementGuid>3b98f910-6664-433e-a09f-0c54ba6d14d5</webElementGuid>
    </webElementProperties>
</WebElementEntity>