<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f47e3d13-f4b7-46ce-aab6-19e5f6a94ef7</elementGuidId>
    <imagePath></imagePath>
    <name>button_ProceedToCheckout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"tag_name": "svg"}], "css": ["[class=\"btn\\ btn-action\\ btn-lg\\ btn-anim\"]"], "self": {"class_name": "btn btn-action btn-lg btn-anim"}, "smart": ["internal:role=button[name=\"Proceed to checkout\"i]"], "target_attributes": {"text": "Proceed to checkout "}, "xpath": "//html/body[1]/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-action\ btn-lg\ btn-anim"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Proceed to checkout"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>