<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ddebf98a-7f5c-4afd-9a68-0eae6b7c1610</elementGuidId>
    <imagePath></imagePath>
    <name>item_CartItem</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"class_name": "", "tag_name": "div"}], "self": {"class_name": "horizontal-menu__root-element has-children"}, "target_attributes": {}, "xpath": "//html/body[1]/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]"}]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>