<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6404bf69-eda8-49bf-944c-5e43c6b69c99</elementGuidId>
    <imagePath></imagePath>
    <name>div_PaymentMethod</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[1]/div[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiStep-root\ MuiStep-horizontal\ MuiStep-alternativeLabel\ css-166ciyp"]:nth-child(3)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text=/^3Payment method$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>