<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fee3fdbd-428e-47d2-8734-0e7ccb995fd9</elementGuidId>
    <imagePath></imagePath>
    <name>button_quantityAction</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[type="button"]:nth-child(3)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="${button_quantityAction_internalRoleButtonName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>