<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8dd34dcb-6ca1-4e6f-85fe-800632f2a999</elementGuidId>
    <imagePath></imagePath>
    <name>link_Unknown</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cart-header\ cart-header_active"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="4"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>