<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4fa1641e-ec88-4874-b2d0-305f5fe79aae</elementGuidId>
    <imagePath></imagePath>
    <name>link_Apple</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"class_name": "title", "tag_name": "span"}], "css": ["[class=\"horizontal-menu__child-element\"]:nth-child(1) &gt; [class=\"horizontal-menu__element\\ is-link\\ is-child\"]"], "self": {"class_name": "horizontal-menu__element is-link is-child"}, "smart": ["internal:role=link[name=\"Apple\"i]"], "target_attributes": {"href": "/category/chekhly-na-iphone", "text": "Apple"}, "xpath": "//html/body[1]/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/ul[1]/li[1]/a[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__child-element"]:nth-child(1) &gt; [class="horizontal-menu__element\ is-link\ is-child"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Apple"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>