<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3425ba7c-09f6-41a6-b261-877d86459505</elementGuidId>
    <imagePath></imagePath>
    <name>button_ContinueToPayment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"class_name": "MuiTouchRipple-root css-w0pj6f", "tag_name": "span"}], "css": ["[class=\"MuiButtonBase-root\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeMedium\\ MuiButton-containedSizeMedium\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeMedium\\ MuiButton-containedSizeMedium\\ css-1hw9j7s\"]"], "self": {"class_name": "MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium css-1hw9j7s"}, "smart": ["internal:role=button[name=\"Continue to payment\"i]", "form &gt;&gt; internal:role=button"], "target_attributes": {"text": "CONTINUE TO PAYMENT", "type": "submit"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[3]/button[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ css-1hw9j7s"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Continue to payment"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>