<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>50512a7d-aebf-4595-ba6c-ea7a63ffc5fd</elementGuidId>
    <imagePath></imagePath>
    <name>completeOrderButton</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ css-1hw9j7s"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'COMPLETE ORDER')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Complete order"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>COMPLETE ORDER</value>
        <webElementGuid>852be597-16fc-442a-b8cc-23bc2563544a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>852be597-16fc-442a-b8cc-23bc2563544a</webElementGuid>
    </webElementProperties>
</WebElementEntity>