<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e3cf98b9-6520-4d0c-90f0-3da0f5fa666e</elementGuidId>
    <imagePath></imagePath>
    <name>div_CheckoutInfo3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [{"class_name": "MuiInputBase-input MuiInput-input css-mnn31", "tag_name": "input"}], "self": {"class_name": "MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl css-12rx5qu"}, "target_attributes": {}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[3]/div[1]/div[1]"}]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>