<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8bb797b2-efa1-4374-bad2-53027b233af4</elementGuidId>
    <imagePath></imagePath>
    <name>input_ZipCode2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [], "css": ["#\\:r5\\:"], "self": {"class_name": "MuiInputBase-input MuiInput-input css-mnn31"}, "smart": ["internal:label=\"ZIP code *\"i"], "target_attributes": {"id": ":r5:", "label": "ZIP code\u2009*", "name": "shipping_address.zip", "type": "text"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[4]/div[1]/div[1]/input[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r5\:</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="ZIP code *"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>