<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ea07140f-fa0c-42b9-bdc6-f9f559bba6c4</elementGuidId>
    <imagePath></imagePath>
    <name>input_Phone2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [], "css": ["#\\:r8\\:"], "self": {"class_name": "MuiInputBase-input MuiInput-input css-mnn31"}, "smart": ["internal:label=\"Phone\"i"], "target_attributes": {"id": ":r8:", "label": "Phone", "name": "shipping_address.phone", "type": "text"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[7]/div[1]/div[1]/input[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r8\:</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Phone"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>