<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>192d74d2-722c-4154-82d0-2c119a940584</elementGuidId>
    <imagePath></imagePath>
    <name>input_FirstName2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [], "css": ["#\\:r2\\:"], "self": {"class_name": "MuiInputBase-input MuiInput-input css-mnn31"}, "smart": ["internal:label=\"First name *\"i"], "target_attributes": {"id": ":r2:", "label": "First name\u2009*", "name": "shipping_address.first_name", "type": "text"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r2\:</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="First name *"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>