<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d628bfb5-f91f-4d72-97e4-7904f10b1541</elementGuidId>
    <imagePath></imagePath>
    <name>input_City2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"children": [], "css": ["#\\:r6\\:"], "self": {"class_name": "MuiInputBase-input MuiInput-input css-mnn31"}, "smart": ["internal:label=\"City *\"i"], "target_attributes": {"id": ":r6:", "label": "City\u2009*", "name": "shipping_address.city", "type": "text"}, "xpath": "//html/body[1]/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[5]/div[1]/div[1]/input[1]"}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r6\:</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="City *"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>