<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>123dda1d-bc14-4d1d-96ba-3251f489c571</elementGuidId>
    <imagePath></imagePath>
    <name>progressbar_loadingLine</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiLinearProgress-root\ MuiLinearProgress-colorPrimary\ MuiLinearProgress-determinate\ bdl-loading-line__linear\ bdl-loading-line__linear_finished\ css-7p5u54"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=progressbar</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>