<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4d25d1f2-84e3-4040-ba29-ebcdd224ee79</elementGuidId>
    <imagePath></imagePath>
    <name>link_ContactNumber</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/footer[1]/div[1]/div[1]/div[3]/p[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="page-footer__icon-w-link"]:nth-child(2) &gt; [class="link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'tel:+18001234567') and equals(@text,'+1 (800) 123-45-67')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=contentinfo &gt;&gt; internal:role=link[name="+1 (800) 123-45-"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>tel:+18001234567</value>
        <webElementGuid>483062ef-248b-48a0-b6ce-99336afd92c8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+1 (800) 123-45-67</value>
        <webElementGuid>483062ef-248b-48a0-b6ce-99336afd92c8</webElementGuid>
    </webElementProperties>
</WebElementEntity>