<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0c4072f8-ceb1-4ec2-b029-ce4a10e5f215</elementGuidId>
    <imagePath></imagePath>
    <name>button_cartAction</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-outline-secondary\ text-center"]:nth-child(${button_cartAction_nthChild})</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="${button_cartAction_internalRoleButtonName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>