<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8d9491be-9387-4e09-883c-eb4de6ac8597</elementGuidId>
    <imagePath></imagePath>
    <name>link_20WusbcpowerAdapter</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(1) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-20w-usb-c-power-adapter?sort=title&amp;category=99') and equals(@text,'20W USB-C Power Adapter')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="20W USB-C Power Adapter"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-20w-usb-c-power-adapter?sort=title&amp;category=99</value>
        <webElementGuid>664de9d3-2bc4-4d3f-a914-a0dfcf7ddfd4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>20W USB-C Power Adapter</value>
        <webElementGuid>664de9d3-2bc4-4d3f-a914-a0dfcf7ddfd4</webElementGuid>
    </webElementProperties>
</WebElementEntity>