<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6853961e-7178-48c0-85b5-1db46ee0d936</elementGuidId>
    <imagePath></imagePath>
    <name>link_20WusbcpowerAdapter</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-20w-usb-c-power-adapter?sort=title&amp;category=99') and equals(@text,'20W USB-C Power Adapter')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="20W USB-C Power Adapter"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-20w-usb-c-power-adapter?sort=title&amp;category=99</value>
        <webElementGuid>6c7eff38-3f46-4210-9e61-6f8ae163b903</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>20W USB-C Power Adapter</value>
        <webElementGuid>6c7eff38-3f46-4210-9e61-6f8ae163b903</webElementGuid>
    </webElementProperties>
</WebElementEntity>