<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>75c0fab9-f0ee-4299-9a50-64a73fda4726</elementGuidId>
    <imagePath></imagePath>
    <name>list_HotNewProducts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products\ list-unstyled\ products_in-category\ mt-2\ mb-4"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Hot! New!iPhone 15From:$ 799.00 New!iPhone 15 PlusFrom:$ 1,200.00$ 899.00 Hot!"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>